In [1]:
import numpy as np
import pandas as pd

Q1. Write a NumPy program to swap rows and columns of a given array in reverse order.

In [2]:
array1 = np.random.randint(1,100,50)
array1 = array1.reshape(5,10)
print(array1)


[[63 84 48 84 32 62 38 26 55 51]
 [ 6 16 65 83 38 99 64 18  7  1]
 [57 65 38 48 92 42 25  8 42 91]
 [71 73 74 13 67 70 61  7 96 50]
 [46 52 88 63 57 74 10  2 77 40]]


In [3]:
array1 = array1[::-1,::-1].T
print(array1)


[[40 50 91  1 51]
 [77 96 42  7 55]
 [ 2  7  8 18 26]
 [10 61 25 64 38]
 [74 70 42 99 62]
 [57 67 92 38 32]
 [63 13 48 83 84]
 [88 74 38 65 48]
 [52 73 65 16 84]
 [46 71 57  6 63]]


Q2.(a). Write a NumPy program to find the most frequent value in an array.

array:
[6 9 5 1 4 6 7 8 9 8 7 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 
6 3 4 5 9 7 2 7 0 2 2 6]


In [4]:
array2 = np.array([6, 9, 5, 1, 4, 6, 7, 8, 9, 8, 7, 1, 7, 5, 1, 0, 1, 5, 5, 0, 8, 9, 0, 7, 0, 7, 6, 5, 1, 1, 9, 5, 3, 8, 7, 9, 
6, 3, 4, 5, 9, 7, 2, 7, 0, 2, 2, 6])
freq = np.bincount(array2)
print(freq)

[5 6 3 2 2 7 5 8 4 6]


In [5]:
freq.argmax()

7

(b). sort the frequent values in descending order

In [6]:
unq = np.nonzero(freq)[0]
freqs = freq[unq]
print(unq)
print(freqs)


[0 1 2 3 4 5 6 7 8 9]
[5 6 3 2 2 7 5 8 4 6]


In [7]:
zipping_sortby_freq = sorted(zip(unq,freqs),key=lambda x:x[1],reverse=True)
print(zipping_sortby_freq)

[(7, 8), (5, 7), (1, 6), (9, 6), (0, 5), (6, 5), (8, 4), (2, 3), (3, 2), (4, 2)]


In [8]:
value_sortby_freq = [values for values,freqencies in zipping_sortby_freq]
print(value_sortby_freq)

[7, 5, 1, 9, 0, 6, 8, 2, 3, 4]


Q3- Write a Pandas Program to create a dataframe such that the column labels are Name, Rollnumber, Subject1, Subject2 and Total

i)	Using Pandas function itself calculate the statistical summary(mean, median, mode, Quartiles, etc) of all the numerical columns.


In [9]:
data = [["Abhishek",3,89,76,165],["Shruti",4,80,69,149],["Karan",25,84,78,162],["Kalash",24,93,83,176],["Jaimeen",23,79,82,161]]
dataframe = pd.DataFrame(data,columns=["Name","Roll Number","Subject1","Subject2","Total"])
dataframe

Name  Roll Number  Subject1  Subject2  Total
0  Abhishek            3        89        76    165
1    Shruti            4        80        69    149
2     Karan           25        84        78    162
3    Kalash           24        93        83    176
4   Jaimeen           23        79        82    161

In [10]:
dataframe.describe()

Roll Number   Subject1  Subject2       Total
count     5.000000   5.000000   5.00000    5.000000
mean     15.800000  85.000000  77.60000  162.600000
std      11.256109   5.958188   5.59464    9.659193
min       3.000000  79.000000  69.00000  149.000000
25%       4.000000  80.000000  76.00000  161.000000
50%      23.000000  84.000000  78.00000  162.000000
75%      24.000000  89.000000  82.00000  165.000000
max      25.000000  93.000000  83.00000  176.000000

ii)	Sort the entire dataframe based on the alphabetical order 

In [11]:
dataframe.sort_values("Name")

Name  Roll Number  Subject1  Subject2  Total
0  Abhishek            3        89        76    165
4   Jaimeen           23        79        82    161
3    Kalash           24        93        83    176
2     Karan           25        84        78    162
1    Shruti            4        80        69    149

iii)	Change the dataset such that there are missing values and NAN values in the dataset and handle them appropriately.

In [12]:
gender = pd.Series(["Female","Male","Male"],index=[1,2,3])
gender

1    Female
2      Male
3      Male
dtype: object

In [13]:
dataframe["Gender"]=gender
dataframe

Name  Roll Number  Subject1  Subject2  Total  Gender
0  Abhishek            3        89        76    165     NaN
1    Shruti            4        80        69    149  Female
2     Karan           25        84        78    162    Male
3    Kalash           24        93        83    176    Male
4   Jaimeen           23        79        82    161     NaN

In [14]:
dataframe.fillna("No Gender")

Name  Roll Number  Subject1  Subject2  Total     Gender
0  Abhishek            3        89        76    165  No Gender
1    Shruti            4        80        69    149     Female
2     Karan           25        84        78    162       Male
3    Kalash           24        93        83    176       Male
4   Jaimeen           23        79        82    161  No Gender